name: OpenSource Development by Android-Andi @ XDA
description: OpenSource Development by Android-Andi
repository: andi34/andi34.github.io
url: http://andi34.github.io
baseurl: ""

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

  -
    scope:
      path: "changelog"
    values:
      layout: "changelog"
      single: "true"

  -
    scope:
      path: "faq"
    values:
      layout: "faq_tutorial"
      single: "true"

permalink: none

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules/
  - assets/scss/
